name = "hugo-theme"
license = "MIT"
licenselink = "https://github.com/laszloszurok/hugo-theme/blob/main/LICENSE"
description = "A minimal hugo theme."
homepage = ""
tags = ["minimal", "dark", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "László Szurok"
  homepage = "https://pulzar.envs.net"
